// Offline training entrypoint: fits the viability scorecard on the synthetic
// train split and writes the fitted artefact (src/lib/scoring/model.json) plus a
// bank-grade model card (docs/model-card.md). Run with: npm run train.

import { writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { generateDataset } from "../src/lib/data/generate";
import { trainModel, splitTrainTest } from "../src/lib/scoring/train";
import { TERM_DEFS } from "../src/lib/scoring/ml-terms";

const here = dirname(fileURLToPath(import.meta.url));

const all = generateDataset(1000);
const { train, test } = splitTrainTest(all);
const model = trainModel(train, test, { epochs: 2000, lr: 0.2, l2: 1e-3 });

writeFileSync(
  resolve(here, "../src/lib/scoring/model.json"),
  JSON.stringify(model, null, 2) + "\n",
);

const m = model.metrics;
const termRows = TERM_DEFS.map((t) => {
  const f = model.terms[t.key];
  const dir = f.weight === 0 ? "≈ neutral (redundant)" : f.weight > 0 ? "↑ default" : "↓ default";
  return `| ${t.label} (\`${t.key}\`) | ${f.weight.toFixed(3)} | ${dir} |`;
}).join("\n");

const card = `# IDBI MSME HealthLens — ML Model Card

> Generated by \`npm run train\`. Synthetic data only — NOT production-calibrated.

## Purpose
A transparent logistic scorecard that estimates an MSME's **viability** (1 − probability of default) from consented alternate data. It is a secondary, explainable AI signal on the Health Card; it never overrides the rule-based HealthScore or the BRE decision.

## Label
\`synthetic_default\` — a leakage-free, stochastic Bernoulli draw from each MSME's hidden \`latent_default_propensity\`. No model feature is a deterministic function of the label.

## Data
- Synthetic population: ${all.length} MSMEs (deterministic seed).
- Train: ${m.trainN} · Held-out test: ${m.testN}.
- Train default rate: ${(m.defaultRateTrain * 100).toFixed(1)}%.

## Validation metrics (held-out test)
| Metric | Value |
| --- | --- |
| AUC | ${m.auc} |
| KS | ${m.ks} |
| Gini | ${m.gini} |

## Features and fitted direction
| Feature | Weight (standardised) | Effect |
| --- | --- | --- |
${termRows}

> **Electricity / power-consumption signals** (\`powerTrend\`, \`turnoverPowerGap\`) are
> retained as features but show ~0 weight on the full population because they are
> statistically redundant with the cash-flow and GST-vs-bank signals the model has
> already learned. They remain decision-relevant through (a) the rule-based
> **Power & operations** sub-score (10% of the primary HealthScore), (b) the
> power-vs-turnover fraud flag, and (c) thin-file applicants with no GST/bureau,
> where power is the only confirmation of real operating activity. A sign-constrained
> scorecard should not be forced to load a redundant feature for appearances.

## Explainability
For this linear model the per-feature contribution is **exact** (weight × standardised value) — an honest additive explanation. The Explainability screen's contribution bars explain \`mlProbabilityProxy\` only, never the HealthScore.

## Limitations
- Trained on synthetic, schema-faithful data; metrics are illustrative, not production performance.
- In a pilot, refit and calibrate against IDBI's anonymised MSME portfolio with WoE/optimal binning and stronger models (LightGBM), keeping BRE rules as the final control.

## Governance
- Owner: HealthLens credit-decisioning team.
- Final decision authority: IDBI (human-in-the-loop). HealthLens is decision-support only.
- Refit cadence: each dataset/seed change re-runs \`npm run train\` deterministically.
`;

writeFileSync(resolve(here, "../docs/model-card.md"), card);

console.log(
  `Trained on ${m.trainN} / tested on ${m.testN}. AUC=${m.auc} KS=${m.ks} Gini=${m.gini} defaultRate(train)=${m.defaultRateTrain}`,
);
