/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScoreRouteImport } from './routes/score'
import { Route as QueueRouteImport } from './routes/queue'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as GovernanceRouteImport } from './routes/governance'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CasesIdRouteImport } from './routes/cases.$id'
import { Route as CasesIdIndexRouteImport } from './routes/cases.$id.index'
import { Route as CasesIdFraudRouteImport } from './routes/cases.$id.fraud'
import { Route as CasesIdExplainRouteImport } from './routes/cases.$id.explain'
import { Route as CasesIdDecisionRouteImport } from './routes/cases.$id.decision'
import { Route as CasesIdConsentRouteImport } from './routes/cases.$id.consent'
import { Route as CasesIdCamRouteImport } from './routes/cases.$id.cam'

const ScoreRoute = ScoreRouteImport.update({
  id: '/score',
  path: '/score',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueRoute = QueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceRoute = GovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesIdRoute = CasesIdRouteImport.update({
  id: '/cases/$id',
  path: '/cases/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesIdIndexRoute = CasesIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CasesIdRoute,
} as any)
const CasesIdFraudRoute = CasesIdFraudRouteImport.update({
  id: '/fraud',
  path: '/fraud',
  getParentRoute: () => CasesIdRoute,
} as any)
const CasesIdExplainRoute = CasesIdExplainRouteImport.update({
  id: '/explain',
  path: '/explain',
  getParentRoute: () => CasesIdRoute,
} as any)
const CasesIdDecisionRoute = CasesIdDecisionRouteImport.update({
  id: '/decision',
  path: '/decision',
  getParentRoute: () => CasesIdRoute,
} as any)
const CasesIdConsentRoute = CasesIdConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => CasesIdRoute,
} as any)
const CasesIdCamRoute = CasesIdCamRouteImport.update({
  id: '/cam',
  path: '/cam',
  getParentRoute: () => CasesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/governance': typeof GovernanceRoute
  '/portfolio': typeof PortfolioRoute
  '/queue': typeof QueueRoute
  '/score': typeof ScoreRoute
  '/cases/$id': typeof CasesIdRouteWithChildren
  '/cases/$id/cam': typeof CasesIdCamRoute
  '/cases/$id/consent': typeof CasesIdConsentRoute
  '/cases/$id/decision': typeof CasesIdDecisionRoute
  '/cases/$id/explain': typeof CasesIdExplainRoute
  '/cases/$id/fraud': typeof CasesIdFraudRoute
  '/cases/$id/': typeof CasesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/governance': typeof GovernanceRoute
  '/portfolio': typeof PortfolioRoute
  '/queue': typeof QueueRoute
  '/score': typeof ScoreRoute
  '/cases/$id/cam': typeof CasesIdCamRoute
  '/cases/$id/consent': typeof CasesIdConsentRoute
  '/cases/$id/decision': typeof CasesIdDecisionRoute
  '/cases/$id/explain': typeof CasesIdExplainRoute
  '/cases/$id/fraud': typeof CasesIdFraudRoute
  '/cases/$id': typeof CasesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/governance': typeof GovernanceRoute
  '/portfolio': typeof PortfolioRoute
  '/queue': typeof QueueRoute
  '/score': typeof ScoreRoute
  '/cases/$id': typeof CasesIdRouteWithChildren
  '/cases/$id/cam': typeof CasesIdCamRoute
  '/cases/$id/consent': typeof CasesIdConsentRoute
  '/cases/$id/decision': typeof CasesIdDecisionRoute
  '/cases/$id/explain': typeof CasesIdExplainRoute
  '/cases/$id/fraud': typeof CasesIdFraudRoute
  '/cases/$id/': typeof CasesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/architecture'
    | '/governance'
    | '/portfolio'
    | '/queue'
    | '/score'
    | '/cases/$id'
    | '/cases/$id/cam'
    | '/cases/$id/consent'
    | '/cases/$id/decision'
    | '/cases/$id/explain'
    | '/cases/$id/fraud'
    | '/cases/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/architecture'
    | '/governance'
    | '/portfolio'
    | '/queue'
    | '/score'
    | '/cases/$id/cam'
    | '/cases/$id/consent'
    | '/cases/$id/decision'
    | '/cases/$id/explain'
    | '/cases/$id/fraud'
    | '/cases/$id'
  id:
    | '__root__'
    | '/'
    | '/architecture'
    | '/governance'
    | '/portfolio'
    | '/queue'
    | '/score'
    | '/cases/$id'
    | '/cases/$id/cam'
    | '/cases/$id/consent'
    | '/cases/$id/decision'
    | '/cases/$id/explain'
    | '/cases/$id/fraud'
    | '/cases/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchitectureRoute: typeof ArchitectureRoute
  GovernanceRoute: typeof GovernanceRoute
  PortfolioRoute: typeof PortfolioRoute
  QueueRoute: typeof QueueRoute
  ScoreRoute: typeof ScoreRoute
  CasesIdRoute: typeof CasesIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/score': {
      id: '/score'
      path: '/score'
      fullPath: '/score'
      preLoaderRoute: typeof ScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue': {
      id: '/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof QueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance': {
      id: '/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof GovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$id': {
      id: '/cases/$id'
      path: '/cases/$id'
      fullPath: '/cases/$id'
      preLoaderRoute: typeof CasesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$id/': {
      id: '/cases/$id/'
      path: '/'
      fullPath: '/cases/$id/'
      preLoaderRoute: typeof CasesIdIndexRouteImport
      parentRoute: typeof CasesIdRoute
    }
    '/cases/$id/fraud': {
      id: '/cases/$id/fraud'
      path: '/fraud'
      fullPath: '/cases/$id/fraud'
      preLoaderRoute: typeof CasesIdFraudRouteImport
      parentRoute: typeof CasesIdRoute
    }
    '/cases/$id/explain': {
      id: '/cases/$id/explain'
      path: '/explain'
      fullPath: '/cases/$id/explain'
      preLoaderRoute: typeof CasesIdExplainRouteImport
      parentRoute: typeof CasesIdRoute
    }
    '/cases/$id/decision': {
      id: '/cases/$id/decision'
      path: '/decision'
      fullPath: '/cases/$id/decision'
      preLoaderRoute: typeof CasesIdDecisionRouteImport
      parentRoute: typeof CasesIdRoute
    }
    '/cases/$id/consent': {
      id: '/cases/$id/consent'
      path: '/consent'
      fullPath: '/cases/$id/consent'
      preLoaderRoute: typeof CasesIdConsentRouteImport
      parentRoute: typeof CasesIdRoute
    }
    '/cases/$id/cam': {
      id: '/cases/$id/cam'
      path: '/cam'
      fullPath: '/cases/$id/cam'
      preLoaderRoute: typeof CasesIdCamRouteImport
      parentRoute: typeof CasesIdRoute
    }
  }
}

interface CasesIdRouteChildren {
  CasesIdCamRoute: typeof CasesIdCamRoute
  CasesIdConsentRoute: typeof CasesIdConsentRoute
  CasesIdDecisionRoute: typeof CasesIdDecisionRoute
  CasesIdExplainRoute: typeof CasesIdExplainRoute
  CasesIdFraudRoute: typeof CasesIdFraudRoute
  CasesIdIndexRoute: typeof CasesIdIndexRoute
}

const CasesIdRouteChildren: CasesIdRouteChildren = {
  CasesIdCamRoute: CasesIdCamRoute,
  CasesIdConsentRoute: CasesIdConsentRoute,
  CasesIdDecisionRoute: CasesIdDecisionRoute,
  CasesIdExplainRoute: CasesIdExplainRoute,
  CasesIdFraudRoute: CasesIdFraudRoute,
  CasesIdIndexRoute: CasesIdIndexRoute,
}

const CasesIdRouteWithChildren =
  CasesIdRoute._addFileChildren(CasesIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchitectureRoute: ArchitectureRoute,
  GovernanceRoute: GovernanceRoute,
  PortfolioRoute: PortfolioRoute,
  QueueRoute: QueueRoute,
  ScoreRoute: ScoreRoute,
  CasesIdRoute: CasesIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
